### ISSUE TITLE
Proposed Update/Modernisation

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#34]
Hi Folks, it's been a little while, I had some time and thought FPA might be due a bit of an overhaul.

This is purely a demo/visual representation, there ate no test/routines included yet, all data/content is hard-coded dummy data.

Although this now makes FPA an "online" (needs an internet connection) application now, this demo includes Bootstrap & jQuery from CDN to improve visual layout, responsiveness and functionality.

The download package includes a few dummy J! folders for testing only and there are temporary external/includes to separate functions for testing purposes only. It is still intentioned for this version of FPA to continue t be a single file script.

_I'd be interested in your thoughts and comments before progressing any further._

**Proposed FPA v2.0.0 Sample**
https://github.com/hotmangoDevelopment/ForumPostAssistant-v2-2018 

Cheers
RussW

**Comment by mandville** [comment]
ill play in the morning. and ping you the url for external testing

**Comment by mandville** [comment]
looking good, i have sent it out to a few trusted people for testing , mainly for people who use the fpa ll the time. 
the current fpa is being translated, https://crowdin.com/project/miscelleanous how does that affect this release?

**Comment by sozzled** [comment]
As I indicated to @mandville, the most important facet of the FPA reporting tool (as far as we, who assist on the Joomla forum are concerned) is to guide people to where they can see the BBcode generated by the tool and how to copy that code ... and, perhaps more importantly, not to post "images" of the FPA report, attach the BBcode as a .TXT file, or embed the BBcode within forum [code] ... [/code] tags.  If we could change people's behaviour, even just a little bit, then any improvement to the FPA tool will be a welcome one.

I've added this .git to my watch list.

**Comment by Webdongle** [comment]
Do we need to setup a database and install or just upload and unzip ?

**Comment by mandville** [comment]
on this alpha just upload and run it wont call your current instal. 

i agree the Generate report text should be in 6ft high letters or infographic to say this is how to do it.

**Comment by Webdongle** [comment]
Looks good except for one thing.  Where the bloody hell is the button to copy the formated info to paste in the forum ?

**Comment by Webdongle** [comment]
![warnings](https://user-images.githubusercontent.com/1115202/40051623-52300102-5833-11e8-8f48-c240e6ca4030.JPG)

**Comment by fcoulter** [comment]
> i agree the Generate report text should be in 6ft high letters or infographic to say this is how to do it.

Yes another vote for this, I did find it difficult to find. For someone who doesn't know what they are looking for it is going to be very difficult. 

The rest of it looks good.

**Comment by sozzled** [comment]
(I hope that the design does not literally involve the use of signage with lettering that's 1.83 metres high)

While I'm not an advocate of dumbing things down too much or publicly embarrassing [seemingly incompetent] people who cannot follow a set of instructions, there are some other ways we can improve the workflow.

The FPA tool performs **_two_** functions:  (1) to advise the site owner of potential problems and (2) to generate BBcode that's suitable for posting on a PHP forum.  Some people, running the FPA, will use it for either or both purposes.  It would therefore be pointless to concentrate all the signage around purpose (2) if the person running the FPA was using it for purpose (1).

There are other ways of attracting the user's attention in relation to purpose (2) above.  One way would be to have a NEXT button at the top of the page (in much the same way as there's a similar feature used in the J! installation procedure) that guides the user to select/copy the BBcode.

But there's a further problem:  because the "powers that be" (who impose the restrictions used at the J! forum site) have restricted posts to less than 20K characters, and most—even "moderately bloated"—J! sites will cause the FPA tool to generate more than 20K characters, chopping the BBcode around is a further hurdle that people have to overcome in order to get the information we need to help them.

As part of this FPA re-vamp project, it might be an idea to see what possibility exists to relax the 20K character limitation on forum posting?  If that's not possible, then as part of this FPA re-vamp, consider the possibility of selecting parts of the FPA report so that they can be posted without breaking the BBcode?  I dunno if it's worth it but, remember, we're mainly dealing with non-intuitive types who can't read English and (even if they do read and comprehend English) won't follow instructions (no matter what sized signage one places in front of them)!

**Comment by Webdongle** [comment]
@sozzled 
> The FPA tool performs two functions: (1) to advise the site owner of potential problems and (2) to generate BBcode that's suitable for posting on a PHP forum. 

Sorry but you are incorrect ... the sole purpose of the FPA is to provide a method to post detailed info in the forum that it is why it is called the Forum Post Assistant not Diagnose Server Assistant.

Being able to copy the details to post formatted for the Forum is paramount and the sole purpose of the tool.

**Comment by sozzled** [comment]
@webdongle:  if your conjecture is the case, there is no need to present the information from the FPA in **_any_** human-readable form at all.  Therefore, by the same reasoning, this FPA "repackaging excerise" is largely a waste of everyone's time.

Obviously—for as long as I've used the FPA tool—**_some_** thought went into the way that information is presented (with colour-coded warnings/advisories, etc.) so that it can be used "offline" from the forum:  it **_does_** provide information that some people may be oblivious to (even if you don't use the FPA for that reason or if you think you know all there is to know about your websites).  I disagree with your assessment:  I am not incorrect even if you think I might be.

**Comment by mandville** [comment]
@frostmakk [mentioned so he can weigh in] colour coded the tags for ease of readability to split core and none core.
i dont hear about users who run the fpa as a diagnose tool pre hacking. but that doesnt mean they dont exist. 
i can request a raise of the character limit but its there to prevent spamming mainly .
The other consideration at current is the language files. It is being translated by crowdin , would we have to repurpose this for v2 in 6 months time?

**Comment by Webdongle** [comment]
@sozzled 
> if your conjecture is the case, there is no need to present the information from the FPA in any human-readable form at all.

No there isn't ... it is just a useful by-product of collecting the information to format for the forum.  The users who are capable of understanding the information can easily find it without using the fpa.  The whole point of the tool is for the info to be readble in the forum so that other users can spot the problem.

It is nice to have a better looking screen and I appreciate the time taken.  However imho it is as useful as a chocolate teapot.  The effort (imho) would be better placed in creating a button to copy the formated info to the clipboard.

It is Forum Post Assistant  it's sole purpose is so that we can better help in the forum when the formatted info is posted there.  There needs to be a big green 'Copy to clipboard' button (with options of what to copy) at the top.

It's difficult enough now to get the users to run it and work out what to copy paste (look how many take a screenshot).  This new format will make it more difficult.

Suggest the screen not have menu options ... just a big green 'Copy to clipboard' button (with options of what to copy).  A discrete 'Advanced' link could be there to open up other options.  But as it is ... it's no use the users who ask for help on the forum.

@sozzled 
Sorry if you don't understand that but I am fed up of having to point out the obvious.  I removed myself from bugsquad because of pompous ignoramuses that made stupid non sensible arguments to try and refute the obvious.  And I am retiring from this thread because you are just being ridiculous and failing to understand something so simple.

**Comment by RussW** [comment]
First of all....   
Thanks to everyone for taking the time to have a quick look and comment, appreciate the feedback and the effort and thought you have put your replies.

**PURPOSE & USE**
@Webdongle, Sorry to burst your bubble here mate, but...  
As the original developer of this concept and script, it was actually designed to be a Security Diagnostic and Reporting tool (it used to be named "_**Joomla Tools Suite** (JTS)_" _(and it was MTS before that, Mambo Tools Suite)_ back in the day and was part of my Security and Penetration Testing tool set that was used by myself and several of the Security Team & Forum Mods & Admins _before the JSST even existed_.)  It was not initially designed for forum posts, that functionality was only added later by myself in an effort to save time for the Security Forum Admins, Mods & Admins with tremendous help from **Mandeville** and **PhilD**, hence the visual UI component.  The script was renamed to FPA due to the new BBCode Post functionality and to make it "recognisable" as a Forum Tool to end-users.

Your "sole use" of FPA may be purely in the forums, that doesn't mean that is all it is used for.  Over the years it has been used by many other Joomla! based groups for many different purposes, none of which included use of the BBCode section. (Server & Site Administrator Education, Server & Site Auditing Reports, Client Reports, Testing unknown server environments prior to installing J!)

**GENERATE BIG GREEN BUTTON**
As for the "Big Green Button, admittedly, at this time, it's not green, but it is a pretty darn big orange button, right under the output textbox. The issue with having a "Copy To Clipboard" button is security, many browsers implement security settings that stop these functions from working to safeguard the user.  

**GENERATE OUTPUT SECTION**
I might not have got the "new" Generate & Output section right, but as this was a "proposed alpha" there is obviously plenty of room to move on that point and I'm actually looking at another layout as we speak, due to the constructive comments in this discussion.

**POST CHARACTER LIMIT**
The 20K post limit has become an issue over time as more and more information as been requested to be added to the BBCode output, a mitigation function had been added but appears not to have solved the UX issue, this is being looked at as part of the process.

**TRANSLATIONS**
At the moment, this "alpha" proposal version has no real test/routine logic in it, only demo/test BBCode output and all test output is hardcoded dummy data.  The language definitions/strings are not complete or set-in-stone, where ever possible it is the intention to re-use existing strings to save re-translation.

**GOING FORWARD**
At the end of the day, if, has been mentioned previously that a re-write and modernisation of FPA is not felt to be needed or of use, then we simply publicly archive the repository and nothing changes.  It certainly isn't worth generating any angst or arguments over, which unfortunately appears to have already occurred!

**Comment by fcoulter** [comment]
RussW I think that in the entire history of humanity there has never been a proposed change to anything anywhere that has not generated angst and arguments and a lot of hot air so I would not let that deter you.

Personally I do think that a rewrite of the FPA is worth doing. When I tested it I liked the new layout, and actually I think that it could be useful outside of generating the forum post content. 

But I did find it hard to find where to do that, I that it would help a lot if that could be made clearer. Perhaps a menu heading for 'Generate Forum Post'? Preferably the first menu item after 'Home' and above 'Basic Discovery', and maybe with a background in green in a similar way to the 'Delete' item has a background in red.

Then there should be a section heading 'Generate Forum Post' which contains the options for FPA Settings and Forum Post Content, in the same layout as now with the accordion panels but maybe a more stand-out colour scheme, eg a green background. Also a brief explanation of how to generate the post.

I hope that makes sense.

I think that would be clearer.

**Comment by Webdongle** [comment]
@fcoulter 
>Perhaps a menu heading for 'Generate Forum Post'? Preferably the first menu item after 'Home' and above 'Basic Discovery',

Far better no menu until a subtle 'Advanced' link is clicked.  


@RussW 
>I am not knocking your efforts.  Just think that the details should not be immediately seen.  Displaying the details is a useful side effect but of no use as a Forum Post Assistant.  The newbies vary from morons to inexperienced users ... so they need KISS not a menu system.  Without the landing screen being a simple page then the fpa will be of little use in the forum.

**Comment by frostmakk** [comment]
When we look at how many first time users of the FPA that have no clue how to use the tool, it seems clear that the UI needs to be improved. Apart from that I believe the biggest issue for the novice user is, as others have pointed out, the 20k character limit.
I don’t mind a fancy UI, loaded with information, as long as it is intuitive, and more or less self-explained. It’s not the size of the letters that matter, it’s that things are where the user expect them to be.
What’s to be done under the hood? Are we talking about a complete rewrite?
The FPA today is compatible with all Joomla versions all the way back to stone age 1.0.  Is this still mandatory? We could get rid of quite a few else if’s, if we draw a line somewhere.
I also feel that some of the information the tool harvest should be re-evaluated. Things that were important before, like magic quotes, is hardly worth checking today. And what useful information is currently missing?
I welcome a makeover of both the UI and the engine, and will participate as best as I can with my limited knowledge.

**Comment by RussW** [comment]
@frostmakk thanks for the comments and thoughts, like you I believe that some content items can be removed and possibly some new options added. We can work on this list as we go forward, at the moment I would like to concentrate on improving the initial "new" user UI experience where possible.

**GENERATE POST SECTION**
I've now removed the User Settings Panel accordion and moved to a "tab" layout as a trial.
[Latest Update .zip Package](https://github.com/hotmangoDevelopment/ForumPostAssistant-v2-2018/archive/master.zip)

_The code's certainly not "cute" at the moment (close your eyes if you view the source at that section) but the basic structure is there._

_All though there is no test logic still, if click any of the tabs, or the "Runtime Options" button or you change the privacy options and click the "Generate Post Now!" button it should give you a rough idea of how I thought it may work in the long run._

_I've also changed the "FPA Version Checking" to now only show the alert if FPA is out-of-date, otherwise the version is displayed and clicking the "?" button will show the alert message for up-to-date or ahead/dev versions) No point in filling the screen with good-news alerts._

@Webdongle
_lotsa **Big Green Buttons** (& Big Blue Tabs) for you and a "Copy To Clipboard Button" in the output..._

**Comment by Webdongle** [comment]
@RussW 
Thanks for listening ... it looks great and the workflow is good.  Couldn't be easier ... download zip, unpack, upload fpa-en.php, point your browser and follow the onscreen instructions.  Simple as abc.

I do have a question.  Is 'strict' privacy settings necessary? It shows little of any real use.

**Comment by frostmakk** [comment]
Just uploaded a PR with the latest changes I have been working on.
Will now take a break from FPA 1.x and await the 2.0 development.

**Comment by mandville** [comment]
'strict' privacy  is a real pain, how many times has it been posted with that just for us to say its a WOAP !

**Comment by RussW** [comment]
I've just setup a [Project Board](https://github.com/orgs/ForumPostAssistant/projects/1) for idea's for new/remove/change feature planning, if you wish to add your idea's and thoughts there for _specific updates_.  I've also added a new [Advisors & Reviewers Team](https://github.com/orgs/ForumPostAssistant/teams/advisors-reviewers) for those wishing be able to provide their feedback on the v2 planning side of things. 

**Strict Privacy**
I've just looked at the **Strict Privacy** output and yes, I can see how some of the masking can be restrictive and limit the ability to assist.  I do think though that it is still needed in some of the circumstances, especially considering things like IP Addresses & hostnames (Remembering this information is public in the forum & FPA does get left on servers sometimes).  I think maybe a reduction in the masking, such as only masking the table prefix ( [xyz]_tablename ) might be better, remove the masking rom the extension names, but continue to mask anything that identifies host, location, user/group details. _**How does that sound?**_

**Comment by sozzled** [comment]
I don't have much of an opinion, either way, about "strict privacy" output:  I would prefer that, most of the time, people didn't use it when posting the FPA BBcode on the forum (because, as @Webdongle writes) it's of lesser practical use to those of us trying to help others.  I suspect (without any evidence to support my conclusion) that people use the strict privacy settings in one of two scenarios:

a)  because the instructions at the forum state that the FPA is a "use at your own risk" (and that there may be potential side-effects if people use the FPA), people may feel more comfortable if they use the strict privacy settings; or
b) strict privacy keeps the BBcode shorter (possibly within the 20K character limit) ... I dunno.

Keep the strict privacy option in the new version (just to keep the people in category (a) above happy) even if it's a burden that we, who read these posts, have to wear.  *sigh*

**Comment by Webdongle** [comment]
@RussW 
Those links appear to be broken.

**Comment by RussW** [comment]
@Webdongle just added you to the new Team, I think the links should work once you accept the Team Add.

Others : let me know if you want to be added too

**Comment by Webdongle** [comment]
Cheers @RussW can test and give feed back too.  Unfortunately can't help with code.

**Comment by RussW** [comment]
**New Function Updates/Changes :** 
- Testing of a standalone VEL Check option
- "Post Output" tab disabled until after "Generate Post" button clicked
- Added new "Show Report Only" option button
- Added (forgotten) form "Reset" button
- Added "Export To CSV" option on selected tabular data
- Changed "Privacy Option" buttons to generic colouring, instead of "Traffic Light" colouring (removing any inference of preferred/best/dangerous selection)

> [Latest Update](https://github.com/hotmangoDevelopment/ForumPostAssistant-v2-2018/archive/master.zip)

**Comment by Webdongle** [comment]
Perhaps with the 'show report only'/'back to fpa' buttons ... 
With 'show report only' showing then no menu no scroll down to basic settings only.  Because when 'back to fpa' is showing then non of the report is showing and clicking it should only show the fpa report not both ?

i.e. It defies logic to click A and show B but click B and show both A .and. B

**Comment by mandville** [comment]
i love the tour thing..

**Comment by sozzled** [comment]
I think this discussion has been overtaken by other events and should be closed.
