### ISSUE TITLE
github location

### ISSUE THREAD

**Issue by brianteeman** [ForumPostAssistant/FPA#38]
shouldnt this be under the joomla-projects account?

**Comment by RussW** [comment]
It started as a "proposal", hence being under one of my own accounts, my plan was once we got the UI under our belts and a group of people that were interested in building the v2, then I'd move it over to the Official FPA account as a branch...  I guess maybe it's that time?

**Comment by brianteeman** [comment]
let me know and i can make the appropriate requests

**Comment by sozzled** [comment]
For the present I would like to keep this proposal relatively quiet (away from the hurly-burly of the Joomla Git), not that I don't consider the input from a broader group to be unhelpful but because it may become difficult to keep our efforts focused.  Up to this point the **_development_** effort in building the software has been in the hands of one or two **_workers_**; the rest of us are "supervisors" (hah-hah).

FPA v2 is barely past the conceptualising phase.  When there's a more viable demo available then, sure, we should take further steps to seek a wider Git audience (knowing, of course, that the broader involvement will try to change the goal-posts, redesign the interface and probably undo the work we few have already attempted).  I guess it makes sense, though, not to have two FPA redesign projects running in parallel or in conflict with one another.

Conceptualising any new proposal necessarily involves both a technical and a user-focused POVs.  I'm not saying that broadening the horizons—settling this mini-project under the broader Joomla Git umbrella—is wrong; I'm only saying that we've barely begun identifying the parts we need (let alone have we commenced designing the parts) before we've begun the assembly.  So, if FPA v2 is moved now, that may be good or it may be bad (I don't know) but the sheer volume of noise may be deafening; I may not be able to handle it.

There are other people whom we respect who do more than their fair share of helping out on the forum.  We might want to reach out to them to seek their input in working out the needs of FPA v2.

**Comment by brianteeman** [comment]
It's nothing to do with noise but about joomla code living under the project and having the visibility to be improved by the entire project.

**Comment by brianteeman** [comment]
And it should never be about limiting the input to people you like/respect. That's completely against the ethos that joomla is built upon.

**Comment by sozzled** [comment]
Yeah, yeah, yeah.  I'm cleaning the dust off my ear-plugs already, mate.

**Comment by mandville** [comment]
Is this actually joomla core code that belongs on joomla properties or is it a code developed by joomla people to assist joomla users?
yes, the fpa1 is on crowdin under a joomla project for translations but that again is not joomla core code.

**Comment by RussW** [comment]
_**IMHO**_ : FPA v1 has always been a minor and third-party project although used quite extensively in the early days. With the improvements offered by Joomla! and the hosting industry in general it is less of a "required tool" today and more of a "useful tool".

It's never been part of the main Joomla! Project and has never been sanctioned by, or directly associated with the Project as a whole.  If it were, there are far better developers in that group, that could do some smarter stuff than I did initially.

For me personally, although I'm not adverse to the idea, I think that unless there is a formal/official request for FPA to be included under the Official Project umbrella from the Project/PLT/Marketing etc, then it continues to stay as a side-project within it's own Github environment. 

_AND_, at this time, the _**v2 development repository**_ also stays off the Official FPA Github page until there is more to show, otherwise there will potentially be downloads and (as mentioned) some unnecessary "white-noise" in the early stages.

**Comment by RussW** [comment]
_If there's no opposition or alternative options to this outcome at this time, shall we close?_
