### ISSUE TITLE
PHP Notice: Undefined index: cmsRELEASE in C:\wamp64\www\atelier_fixed\fpa-en.php on line 3726

### ISSUE THREAD

**Issue by Webdongle** [ForumPostAssistant/FPA#48]
Spotted when posted to forum https://forum.joomla.org/viewtopic.php?f=708&t=965082&p=3538024#p3538024

**Comment by frostmakk** [comment]
cmsRELEASE does not exist on line 3726 in any versions i have checked. Is this a modified file?
This error would indicate that the version.php file is missing or corrupt. This error was most likely not generated by the forum post linked to, because the value of cmsRELEASE is present in this report.
The error is probably generated a bit earlier, possibly when run on a broken file system.

**Comment by Webdongle** [comment]
OK thanks.  will close
