### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by Webdongle** [ForumPostAssistant/FPA#56]
I find

> A standalone PHP script to help end-users collect and subsequently post diagnostic and configuration information in to a forum post when asking for assistance to resolve problems or issues with their Joomla!® web-site.

Difficult to read.  Perhaps the font colour could be black?

**Comment by RussW** [comment]
Assuming you are talking about the heading text on the documentation site, black would not be enough contrast with the background blue and would be completely unreadable, white, as you can see from the heading, is high contrast, I'd be thinking that it would be a bit too much "in-your-face"...
_(BTW: the docs site has it's own repo, so issues etc can be managed there separately to avoid clogging up the FPA repo with unrelated info)_

If others agree, then it'll be changed to white, otherwise, for me, it works well as it is without being to bright or becoming unreadable.

Anyone else having trouble reading the heading intro text?
